# Generated by Django 5.0.4 on 2024-06-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_diagnostics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_icd_diagnosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_conclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reception_type',
            field=models.CharField(choices=[('ON', 'Онлайн'), ('OFF', 'Оффлайн'), ('BTH', 'Обидва')], default='ON', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='recipe',
            field=models.CharField(choices=[('STEM', 'Так, стимулятори'), ('NSTEM', 'Так, нестимулятори'), ('NO', 'Ні')], default='NO', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='Kyiv', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('PSI1', 'Психолог'), ('PSI2', 'Психотерапевт'), ('PSI3', 'Психіатр'), ('DEF', 'Default')], default='DEF', max_length=100),
        ),
    ]
